### ISSUE TITLE
Photon Collection - Add Script Interface

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#416]
## Request Type
**Feature Request**

## Information
**Photon Collection** - Add Script Interface, with documentation.

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

**Comment by Chadori** [comment]
## Tasks
- [x] **Photon Realtime**: Addon
- [x] **Photon Chat**: Addon
- [x] **Photon Realtime**: Website Documentation
- [x] **Photon Chat**: Website Documentation

**Comment by Chadori** [comment]
**Addons completed**.

New version:
- **Photon Realtime**: `6.1.0.0`
- **Photon Chat**: `6.1.0.0`

Methods:
- `Context` (Returns the addon's instance context.)
- `Client` (Returns the addon's instance client. LBC for Realtime, and Chat Client for Chat.)
- `Photon` (Returns the global Photon object)

**Comment by Chadori** [comment]
Website documentation completed.

**Comment by Chadori** [comment]
All tasks completed.
Now closed.
