### ISSUE TITLE
[Google Admob Collection] Add new documentations for each advert, settings and UMP

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#580]
## Request Type
**Feature Request**

## Information
[Google Admob Collection] Add new documentations for each advertisement, settings and for the User Messaging Platform consent dialog.

## Tasks
- [x] App Open Ads
- [x] Banner Ads
- [x] Interstitial Ads
- [x] Rewarded Interstitial Ads
- [x] Rewarded Video Ads
- [x] Google Admob (Google Play's Design Apps for Families Programs)
- [x] Google Admob (Regulation Compliance)
- [x] Consent Dialog

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

**Comment by Chadori** [comment]
Now completed
