### ISSUE TITLE
Update all mobile advertisement plugin demo projects

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#581]
## Request Type
**Feature Request**

## Information
Update all mobile advertisement plugin demo projects to apply new mobile settings in Construct 3, and improve how it displays on mobile. This is done by applying either or all of the following:
- [x] Viewport fit to `Cover`
- [x] Fullscreen mode to `Scale outer`
- [x] Web worker mode to `Auto`
- [x] Cordova iOS scheme to `Modern (app:)`
- [x]  Cordova Android scheme to `Modern (https:`

## Tasks
- [x] Mobile IronSource Collection - All to `1.0.0.1`
   - [x] Mobile IronSource (Automatic)
   - [x] Mobile IronSource (Automatic-Advanced)
   - [x] Mobile IronSource (Easy Banners)
   - [x] Mobile IronSource (Google Play's Design Apps for Families Programs)
   - [x] Mobile IronSource (Manual)
   - [x] Mobile IronSource (Manual-Advanced)
   - [x] Mobile IronSource (Manual-Easy Banners)
   - [x] Mobile IronSource (Regulation Compliance)
   - [x] Mobile IronSource (Test App)
- [x] Google Admob Collection - All changes applied to version `2.0.0.0`
   - [x] Demo Project
- [x] Mobile Consent - All changes applied to version `2.0.0.0`
   - [x] Demo Project - Google Admob
   - [x] Demo Project - ironSource
   - [x] Demo Project

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

**Comment by Chadori** [comment]
Now completed
