### ISSUE TITLE
Add mobile advertisement demo projects without the Mobile Info plugin

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#587]
## Request Type
**Feature Request**

## Information
Add mobile advertisement demo projects without the Mobile Info plugin. The alternative plugin that will be used is the `Platform Info` object.

## Tasks
- [x] Mobile Consent
   - [x] Demo Project - ironSource
   - [x] Demo Project - Google Admob
- [x] Mobile IronSource Collection
   - [x] Mobile IronSource (Consent Dialog)
   - [x] Mobile IronSource (Demo Project)
   - [x] Mobile IronSource (Test App with Consent Dialog)
- [x] Google Admob Collection
   - [x] Consent Dialog
   - [x] Demo Project

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

**Comment by Chadori** [comment]
Now completed
