### ISSUE TITLE
[Mobile Firebase] Firebase Analytics and Firebase Remote Config build failure requiring update to latest SDK versions

### ISSUE THREAD

**Issue by Chadori** [Chadori/construct-master-collection#594]
## Request Type
This is a **Bug Report**.

## Describe the bug
[Mobile Firebase] Firebase Analytics and Firebase Remote Config build failure due to outdated versions, now requiring update to latest SDK versions.

## Additional tasks
- [x] Firebase Analytics
  - [x] Update Android SDK version to `21.1.0`.
  - [x] Update iOS SDK version to `9.3.0`.
- [x] Firebase Remote Config
  - [x] Update Android SDK version to `21.1.1`.
  - [x] Update iOS SDK version to `9.3.0`.
  - [x] Explicit removal of `chadori-mobile-firebase-analytics` and explicitly require adding the **Firebase Analytics** plugin as a dependency object.

## Note
This will only be a temporary fix until we can fully upgrade to the latest versions with its new features.

## Tasks
- [x] Firebase Analytics
- [x] Firebase Remote Config

## Construct Editor
 - Construct 3

## Construct Runtime
 - Construct 3

 ## Additional Info
New plugin versions:
- Firebase Analytics (4.0.1.0)
- Firebase Remote Config (2.2.1.0)

**Comment by Chadori** [comment]
Now completed and fixed
